### ISSUE TITLE
Games support

### ISSUE THREAD

**Issue by vladfaust** [hangyas/telegram_bot#22]
None currently found. Also propose to remove the checkmark from _all messages type_ :smirk:

**Comment by hangyas** [comment]
True. To be honest I was lazy and it looked too much work (especially testing), and I wasn't sure if anybody is interested in that functionality anyway.

**Comment by hangyas** [comment]
Wait, I have found them :D 
https://github.com/hangyas/telegram_bot/blob/master/src/telegram_bot/bot.cr#L606
Or is something missing?
