### ISSUE TITLE
Add a way to handle commands and plain messages

### ISSUE THREAD

**Issue by watzon** [hangyas/telegram_bot#23]
The way things are currently set up it doesn't look like it's possible to create commands using the `cmd` method and override the `handle` method for non-command text. This means I have to override the `handle` method and include a check to see if the first character is "/" then duplicate the functionality included in the `TelegramBot::CmdHandler` module.

**Comment by grig191** [comment]
It is possible without any changes:
```ruby
def handle(msg : TelegramBot::Message)
  if text = msg.text || msg.caption
    if text[0] == '/'
      super # Calling CmdHandler
    else
      # Here is your code
    end
  end
end
```
This setup is currently running on my bot and all is OK, so I think we should close this issue and related pull request.

**Comment by grig191** [comment]
@hangyas maybe close this issue?
