### ISSUE TITLE
How do I use ReplyKeyboardMarkup? 

### ISSUE THREAD

**Issue by VanyaNeytrino** [hangyas/telegram_bot#28]
Hi, how do I use ReplyKeyboardMarkup?

**Comment by hangyas** [comment]
It can be initialized with an `Array(Array(String))`: the value of the buttons, then sent as `reply_markup`, when the user clicks a button it's value will be sent as a message

```crystal
keyboard = ReplyKeyboardMarkup.new [["left", "right"], ["down"]]
send_message chat_id, "choose an option", reply_markup: keyboard
```

see: [https://core.telegram.org/bots#keyboards](https://core.telegram.org/bots#keyboards) and [https://core.telegram.org/bots/api#replykeyboardmarkup](https://core.telegram.org/bots/api#replykeyboardmarkup)
