### ISSUE TITLE
The response delay is high, there is no clue

### ISSUE THREAD

**Issue by Hentioe** [hangyas/telegram_bot#39]
I implemented a bot in two different languages ​​and found that the Crystal/TelegramBot has a very high latency.

It takes about two seconds to respond to the api.  Other language frameworks only take a few hundred milliseconds.

I don't see sleep-related code in your framework, no clue.

What do you think is the reason? Thanks!

**Comment by hangyas** [comment]
Hm, no idea.

Did you use web hooks or long pooling?
With which framework did you compare?

**Comment by Hentioe** [comment]
My current situation is that calling the Bot API has a lot of delay, such as `sendMessage`. I am currently running in pooling mode, but even webhook needs to call such APIs, right?

Do you think the problem may be on the HTTP Client?

**Comment by hangyas** [comment]
Well if the other language uses a callback based HTTP client while Crystal's library is blocking (on green threads) that can explain it. (If I'm not mistaken Crystal's behavior is similar to what node.js does if you use await).

with callbacks:
```
log(1)
HTTP.get(url, function(res){ log(res) })
log(2)
---
outputs:
1
2 # waiting for the response
<the request's result>
```

green threads:
```
log(1)
res = HTTP.get(url)
log(res)
log(2)
---
outputs:
1 # waiting for the response
<the request's result>
2
```

I believe you can achieve something like the "callback behavior" with `spawn`, see https://crystal-lang.org/reference/guides/concurrency.html

**Comment by Hentioe** [comment]
It may be related to the server's network, and the delay of other people running my robot locally is very low.

Thank you for your reply!
